# Site
title:              Marta Gómez Macías
bio:                'Estudiante de Ingeniería Informática y apasionada por la fotografía.'
description:        "Soy una estudiante de Ingeniería Informática, especializada en Computación y Sistemas Inteligentes. También me gusta mucho la fotografía, sobre todo de naturaleza y retratos."
reading_time:       false
words_per_minute:   200
logo:               'assets/img/logo.jpe'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             es_ES
url:                https://mgmacias95.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            Mrs_DarkDonado
# facebook:           username
github-url:         mgmacias95
stackoverflow:      7237273/marta-gómez
linkedin:           martagomezmacias
#xing:              username
instagram:          mrs_darkdonado
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
flickr:             mrs_darkdonado
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
500px:              mrs_darkdonado

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
